### ISSUE TITLE
Renombrar artefactos y paquetes Java

### ISSUE THREAD

**Issue by linesta-iti** [iti-ict/wakamiti#122]
Los group en los pom deberian ser es.iti.wakamiti

Renombrar ademas los paquetes java para que empiecen por es.iti.wakamiti

**Comment by mgalbis** [comment]
¿No sería mejor `es.wakamiti`, que ya tiene incluido el `iti`, y así no es tan largo?

**Comment by linesta-iti** [comment]
No pot ser, el grupo que tenemos asociado a la cuenta de sonatype es 'es.iti'  (porque habia que demostrar la posesion de ese dominio de intenet) asi que  todo lo que publiquemos tiene que empezar por eso.
________________________________
