### ISSUE TITLE
Fichero de configuración válido

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#134]
Si el fichero de configuración de wakamiti no es `.yaml` sino `.yml` no lo reconoce como fichero de configuración válido. Debería aceptar ambos tipos de ficheros. 

- Edit:
Parece que el problema está en la clase `imconfig.Configuration` que no contempla la extensión `yml` a la hora de cargar el fichero.

**Comment by juanise** [comment]
True story. Me ha pasado y me costó un día darme cuenta

**Comment by linesta-iti** [comment]
Oido cocina. Lo consideraba un problema menor pero viendo que puede ocasionar esto, haré un parche de la librería de configuración correspondiente para que acepte tanto `yml` como `yaml`.

**Comment by mgalbis** [comment]
- [ ] Actualizar `immutable-config` a versión `1.1.1`

**Comment by mgalbis** [comment]
Se incluye funcionalidad de `immutable-config` en `wakamiti-api`
