### ISSUE TITLE
Plugin email

### ISSUE THREAD

**Issue by linesta-iti** [iti-ict/wakamiti#15]
Crear un plugin para poder leer el correo de una cuenta, mediante SMTP o POP3.

**Comment by auxicarlos** [comment]
Las funcionalidades que estaría bien tener son:

- [ ] leer el título del mensaje
- [ ] leer el remitente 
- [ ] leer el destinatario del correo
- [ ] leer el cuerpo del mensaje
- [ ] borrar el mensaje
- [ ] comprobar si hay adjuntos
