### ISSUE TITLE
Incluir test no ejecutados (por filtrado) en los resultados

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#150]
Incluir en el report los tests que no se han ejecutado por el uso del `tagFilter`.
Esto implicaría la creación de un nuevo [`es.iti.wakamiti.api.plan.Result`](https://github.com/iti-ict/wakamiti/blob/main/wakamiti/wakamiti-api/src/main/java/es/iti/wakamiti/api/plan/Result.java). También se verían afectados los plugins de tipo [`es.iti.wakamiti.api.extensions.Reporter`](https://github.com/iti-ict/wakamiti/blob/main/wakamiti/wakamiti-api/src/main/java/es/iti/wakamiti/api/extensions/Reporter.java) y sería necesario valorar si los test no ejecutados deberían aparecer en esos `Reporter` o no.

**Comment by linesta-iti** [comment]
Creo que la modificacion con menos impacto seria no aplicar el filtro en la construccion inicial del plan, sino directamente en la ejecución (marcarlos ahi como SKIPPED a nivel de caso de test), y como paso posterior, decidir si los TEST_CASE SKIPPED deben incluirse en el json de salida o no, en base a algun parametro.
