### ISSUE TITLE
Error al parsear cuando hay un comentario en la misma línea que los tags

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#169]
Cuando se incluye un comentario en la misma línea que los tags no se generan bien los tags y se rompe el informe html.

```cucumber
@ID-loquesea-01 #Un comentario 
Escenario: El escenario
```
En el informe se genera como:
```
"tags" : ["omentario", "ID-loquesea-01", "Un"]
```

**Comment by linesta-iti** [comment]
Esto es el comportamiento del parseador de Cucumber, en ningun sitio
de la especificacion de Gherkin creo que se diga que se pueden mezclar lineas de comentarios con otro 
tipo de lineas, igual que si pones un comentario al final de un paso, no se interpretara como comentario.

Es verdad que podria dar un error de parseo antes de llegar a ese punto, pero yo lo asumiria como una caracteristica
del lenguaje en vez de un error en si.

**Comment by mgalbis** [comment]
Sí, estaría bien que se quejara o algo que avise porque ahora mismo no te das cuenta. Sería lógico que, para que algo sea considerado tag, cumpla el formato, que es que empiece por @.

**Comment by mgalbis** [comment]
Se ha modificado el gherkin parser para provocar un error si en la línea de tags hay más cosas que no son tags
