### ISSUE TITLE
Mejoras report

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#224]
Cosas a mejorar en el report html:
- Cuando hay muchos tests, al estar todo en una página, se hace poco amigable. Quizás se podría paginar o añadir un filtro por texto que filtre por nombre de escenario o tag. También se hace excesivamente grande el html cuando hay muchos text. Habría que valorar otra forma más eficiente de generar el report.
- Hacer que el texto de cabecera de los escenarios (donde están el título y los tags) sea seleccionable. Añadiendo en el css lo siguiente se podría solventar:
```
  -webkit-user-select: text;
  -moz-user-select: text;
  -ms-user-select: text;
  user-select: text;
```
- Actualmente se genera el html a partir de los resultados de la ejecución con los elementos ya renderizados. Sería mucho más ligero si los elementos se generaran dinámicamente mediante js a partir de los resultados en formato json.
- - [x] #93

**Comment by auxicarlos** [comment]
Filtrar para encontrar un error
Filtrar por tag
Filtrar por escenario
Quitar escenarios listados del desplegable del informe (el que sale al darle a la burguer)
No pintar la excepción de java al fallar un test, si no un mensaje de lo que ha fallado
Que los tags sean seleccionables y no formen parte del desplegable del informe (esto me lo lloran mucho en cierto sitio...)
