### ISSUE TITLE
Error Azure: Mensajes de error sin detalle del error

### ISSUE THREAD

**Issue by tomesla** [iti-ict/wakamiti#233]
Usando el plugin de Azure, el proceso que crea los test suites en Azure ha fallado y el mensaje de error que muestra Wakamiti no contextualiza el motivo del fallo.

![imagen](https://github.com/iti-ict/wakamiti/assets/126468782/e22ca91d-c203-401b-a100-4cad57e58171)

![imagen](https://github.com/iti-ict/wakamiti/assets/126468782/8a5a7fdd-de53-406b-b7a3-9eea39b77c11)

![imagen](https://github.com/iti-ict/wakamiti/assets/126468782/9401d0cc-3a1f-4973-b94d-fd45ed2e0982)

![imagen](https://github.com/iti-ict/wakamiti/assets/126468782/028698dc-3fe6-4b76-9f6b-a4c5226f76c7)

**Comment by mgalbis** [comment]
Sobre la primera captura, para dar algo más de información se podría incluir el código y el mensaje de error cuando el resultado de la llamada no sea satisfactorio.

También se podría añadir alguna política de reintentos o algo así para los casos en los que hay algún problema en la conexión, que es lo que parece que está sucediendo en este caso.

**Comment by linesta-iti** [comment]
Buenas, nos sería util que volvieras a lanzar la ejecución con el parametro `--debug` activo, para ver qué llamadas REST están provocando el error. Gracias!
