### ISSUE TITLE
Al usar protocolo sftp, el fichero ppk indicado no es visible dentro del docker

### ISSUE THREAD

**Issue by linesta-iti** [iti-ict/wakamiti#237]

**Comment by mgalbis** [comment]
El NullPointerException ocurría porque estaban activados todos los tipos de EventObservers (`StandardOutputFilesUploader`, `TestCaseOutputFilesUploader`y `ReportOutputFilesUploader`) con la propiedad `fileUploader.enable: true`. Al no tener configurado el directorio remoto en el observer `StandardOutputFilesUploader` ocasionaba el error.

Se ha añadido una comprobación en la que, si alguno de los observers no tiene ninguna configuración indicada, se desactiva.
