### ISSUE TITLE
No reconoce paso de comprobación de mensaje de respuesta (text)

### ISSUE THREAD

**Issue by BiancaITI** [iti-ict/wakamiti#330]
Requiero un paso que compruebe si la fecha de nacimiento es de alguien nacido hace 18 años, por lo que creamos la comprobación: 
${=use(groovy.time.TimeCategory){ (new Date()-18.year).format('dd/MM/yyyy') }}

Y se la pasamos entre otros a un paso de comprobación de mensaje de respuesta (text). Al lanzar el test no reconoce el paso y da opciones, entre las que se encuentran el mismo paso que estamos usando. Al revisar se puede comprobar que no está realizando la operación en la variable, si no, que lo pasa literal.

Adjunto imágenes del test y la respuesta.
![MicrosoftTeams-image (9)](https://github.com/user-attachments/assets/f3406ca4-b19f-482c-9529-3967deecbbf0)

**Comment by mgalbis** [comment]
No es un error, el problema está en las comillas simples (`'`) de la expresión groovy, que entra en conflicto con las comillas simples del paso y hace que no se reconozca. Es necesario cambiar las comillas simples de la expresión groovy por comillas dobles (`"`).
