### ISSUE TITLE
Defecto en paso de comprobación con tiempo

### ISSUE THREAD

**Issue by BiancaITI** [iti-ict/wakamiti#335]
Usando el paso :
![image](https://github.com/user-attachments/assets/3add923f-6d30-4701-a852-e3df30e0cf4a)
Devuelve el siguiente error:
![image](https://github.com/user-attachments/assets/9e529551-650e-4cc6-83f6-13d96e647b46)
Mientras en BBDD solo existen 3 registros:
Cuando nos hemos dado cuenta, que está sumando los resultados de todas las select que hace durante el tiempo que se indica en el paso, en lugar de parar la primera vez que recibe que hay 3 registros en BBDD.

**Comment by mgalbis** [comment]
Se confirma que se está incrementando el valor de los count cada vez que se comprueba en lugar de setearlo. Se corrige en la próxima versión.
