### ISSUE TITLE
Incluir resulset de las queries en el log

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#40]
Incluir en el log (modo debug o trace) las queries y sus resultados facilitaría mucho la comprobación y desarrollo de los tests.

Contexto:
A la hora de realizar un assert de que existe un registro con x valores en sus campos, se dificulta mucho comprobar el resultado cuando hay muchos registros y/o filtros. Sería interesante añadir alguna funcionalidad que determine qué filtro y qué registro puede estar fallando.

Quizás se podría buscar el registro más parecido, mediante alguna librería como [esta](https://github.com/tdebatty/java-string-similarity).

**Comment by auxicarlos** [comment]
Importante

**Comment by mgalbis** [comment]
Librería interesante que a lo mejor puede ayudar: https://github.com/tdebatty/java-string-similarity
