### ISSUE TITLE
La librería MavenFetcher siempre utiliza por defecto el repositorio de `maven-central`

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#48]
Parece que hay un bug en cuanto al uso de la propiedad `useDefaultRemoteRepository` de la librería MavenFetcher que hace que por defecto se use siempre el repositorio `maven-central=https://repo.maven.apache.org/maven2` y no sea posible de reescribir.

Entiendo que debería borrar los repositorios si la propiedad es `false` en lugar de `true`:
```java
public MavenFetcher config(Properties properties) {
        if ("true".equalsIgnoreCase(properties.getProperty("useDefaultRemoteRepository", "false"))) {
            this.clearRemoteRepositories();
        }
```

**Comment by linesta-iti** [comment]
Se cambia a la version [1.5.0](https://github.com/luiinge/maven-fetcher/releases/tag/v1.5.0) de maven-fetcher.

En esta version, se corrige el bug de la propiedad useDefaultRemoteRepository.
Además, permite indicar credenciales en los repositorios, usando la forma `id=url [user:pwd]`.

**Comment by mgalbis** [comment]
Reabro el issue para que conste que hay que cambiar a la versión `1.5.1` de la librería `maven-fetcher` que corrige el problema del incluir un id con guion, y contraseña con caracteres especiales.
```
22:50:11.642 [main] ERROR iti.kukumo - Error: iti.kukumo.api.KukumoException: Invalid value for property 'remoteRepositories' : Invalid repository value 'maven-central=https://repo.maven.apache.org/maven2/' .
Expected formats are 'id=url' and 'id=url [user:pwd]'
```
