### ISSUE TITLE
Guardar el token en caché para no hacer login en cada escenario

### ISSUE THREAD

**Issue by auxicarlos** [iti-ict/wakamiti#65]
Cuándo en Antecedentes se hace un login y después en un escenario se vuelve a hacer el login, se está utilizando el login del antecedentes y no del Dado.
Este funcionamiento no es correcto, el paso Dado es una inicialización del escenario, si hay un login en ese paso, los siguientes de ese escenario deberían de utilizar ese token y no el de Antecedentes generales del feature

**Comment by mgalbis** [comment]
Se añadirá una funcionalidad para guardar en caché el token recuperado del servicio de oauth2 y poder usarlo en el resto de escenarios.
