### ISSUE TITLE
Desarrollar dashboard para Azure DevOps

### ISSUE THREAD

**Issue by linesta-iti** [iti-ict/wakamiti#7]
Sería bueno desarrollar un **widget** para ver los resultados de Kukumo en el **dashboard de Azure DevOps **... algo similar a lo que tiene [SonarCloud](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarcloud) / [SonarQube ](https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube)
![image](https://user-images.githubusercontent.com/102146178/160114354-5f0ef3f9-1f65-4f85-85ae-bd482fbcdcff.png)

**Comment by auxicarlos** [comment]
util

**Comment by auxicarlos** [comment]
Desarrollado con el plugin de Azure
