### ISSUE TITLE
Añadir paso para forzar a leer la respuesta con un content-type específico

### ISSUE THREAD

**Issue by mgalbis** [iti-ict/wakamiti#85]
Se puede dar el caso en el que, a pesar de recibir un body con formato `json` o `xml`, el `content-type` de la respuesta aparece como `text/plain`, por lo que no se pueden usar los pasos para realizar assert para el tipo de dato real. Es por ello que se podrían añadir pasos para indicarle el `content-type` real con el que debe convertir el body, en lugar de usar el que recibe en la cabecera.

**Comment by auxicarlos** [comment]
Para esto, se debería de utilizar el paso para comprobar el content-type de la respuesta
