### ISSUE TITLE
Informe html v_1.6.0 Falla con navegador Mozilla Firefox

### ISSUE THREAD

**Issue by tomesla** [iti-ict/wakamiti#93]
El nuevo informe html que se genera al lanzar los test.
No funciona correctamente al abrirlo con el navegador Mozilla Firefox.

Al abrirlo con este navegador, no se pueden aplicar los nuevos filtros del informe. El menú para aplicar los filtros nuevos no se muestra al hacer click en el botón.

 Todos los test se muestran desplegados y no se pueden contraer. Al hacer click en el botón para desplegar o contraer la información del test, este se queda siempre desplegado aunque el botón cambie de apariencia.

**Comment by mgalbis** [comment]
El informe utiliza una pseudo-clase (`:has`) en CSS que no se puede usar en Mozilla por defecto, pero, en teoría, a partir de la versión 103 se puede activar la opción `layout.css.has-selector.enabled` que permite su uso.
[Más info](https://developer.mozilla.org/en-US/docs/Web/CSS/:has#browser_compatibility)

**Comment by mgalbis** [comment]
El error se soluciona utilizando una versión más reciente.
